"""shop items

Revision ID: 24d270fb0377
Revises: b8397a187099
Create Date: 2018-08-03 14:32:50.142815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d270fb0377'
down_revision = 'b8397a187099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemType', sa.Integer(), nullable=True),
    sa.Column('string', sa.String(length=16), nullable=True),
    sa.Column('cost1', sa.Integer(), nullable=True),
    sa.Column('cost2', sa.Integer(), nullable=True),
    sa.Column('cost3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_item_string'), 'chat_item', ['string'], unique=True)
    op.create_table('chat_store',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_item_id'], ['chat_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_store')
    op.drop_index(op.f('ix_chat_item_string'), table_name='chat_item')
    op.drop_table('chat_item')
    # ### end Alembic commands ###
