"""more user info

Revision ID: 57462f8c739f
Revises: 34a97cf7a5ed
Create Date: 2018-08-16 14:50:28.998457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57462f8c739f'
down_revision = '34a97cf7a5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('planet_desc', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('theme', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'theme')
    op.drop_column('user', 'planet_desc')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
