"""login

Revision ID: 6a9f29b6e1fc
Revises: f455717e294b
Create Date: 2018-07-27 11:41:08.335146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9f29b6e1fc'
down_revision = 'f455717e294b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticated')
    # ### end Alembic commands ###
