"""added bio, planet_desc, theme

Revision ID: 86f22215c056
Revises: dcc3359be620
Create Date: 2018-08-17 15:15:27.696472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f22215c056'
down_revision = 'dcc3359be620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('planet_desc', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('theme', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'theme')
    op.drop_column('user', 'planet_desc')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
