"""rockets

Revision ID: b8397a187099
Revises: cdeb0710d386
Create Date: 2018-08-02 13:43:05.348210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8397a187099'
down_revision = 'cdeb0710d386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rocket', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rocket')
    # ### end Alembic commands ###
