"""chat color and aliens

Revision ID: cdeb0710d386
Revises: 6a9f29b6e1fc
Create Date: 2018-08-02 13:32:01.214481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdeb0710d386'
down_revision = '6a9f29b6e1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alien', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('chat_color', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chat_color')
    op.drop_column('user', 'alien')
    # ### end Alembic commands ###
