"""added alien event_specific

Revision ID: ce8eca398c67
Revises: c8a811cc4a03
Create Date: 2018-08-22 11:16:49.728011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8eca398c67'
down_revision = 'c8a811cc4a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alien_species', sa.Column('event_specific', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alien_species', 'event_specific')
    # ### end Alembic commands ###
