"""added catalogItem rocket column

Revision ID: dcc3359be620
Revises: 24d270fb0377
Create Date: 2018-08-17 10:45:42.556501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc3359be620'
down_revision = '24d270fb0377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_item', sa.Column('is_rocket', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_item', 'is_rocket')
    # ### end Alembic commands ###
