"""status

Revision ID: f455717e294b
Revises: 
Create Date: 2018-07-19 13:26:22.270779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f455717e294b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('event_specific', sa.Boolean(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('cost1', sa.Integer(), nullable=True),
    sa.Column('cost2', sa.Integer(), nullable=True),
    sa.Column('cost3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_item_name'), 'catalog_item', ['name'], unique=True)
    op.create_table('galaxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galaxy_name'), 'galaxy', ['name'], unique=True)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Boolean(), nullable=True),
    sa.Column('news', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('login_days', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('mission_type', sa.String(length=16), nullable=True),
    sa.Column('mission_current', sa.Integer(), nullable=True),
    sa.Column('mission_total', sa.Integer(), nullable=True),
    sa.Column('cur1', sa.Integer(), nullable=True),
    sa.Column('cur2', sa.Integer(), nullable=True),
    sa.Column('cur3', sa.Integer(), nullable=True),
    sa.Column('vou2', sa.Integer(), nullable=True),
    sa.Column('vou3', sa.Integer(), nullable=True),
    sa.Column('lifetime_cur1', sa.Integer(), nullable=True),
    sa.Column('lifetime_cur2', sa.Integer(), nullable=True),
    sa.Column('lifetime_cur3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('planet_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('catalog_parent_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_parent_id'], ['catalog_item.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('galaxy_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('quadrant', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['galaxy_id'], ['galaxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_name'), 'system', ['name'], unique=True)
    op.create_table('visitors',
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('visited_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['visited_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['user.id'], )
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('surface', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_system_name'), table_name='system')
    op.drop_table('system')
    op.drop_table('planet_item')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('status')
    op.drop_index(op.f('ix_galaxy_name'), table_name='galaxy')
    op.drop_table('galaxy')
    op.drop_index(op.f('ix_catalog_item_name'), table_name='catalog_item')
    op.drop_table('catalog_item')
    # ### end Alembic commands ###
